"""empty message

Revision ID: a8da4521599a
Revises: 12c02549c446
Create Date: 2023-07-26 19:46:38.897251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8da4521599a'
down_revision = '12c02549c446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_company', sa.String(length=255), nullable=False),
    sa.Column('name_fantasy', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=50), nullable=False),
    sa.Column('cnae', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnae')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    op.drop_table('company')
    # ### end Alembic commands ###
